let start = document.getElementById('start'),
    values = document.querySelectorAll('.result-table > div[class*="-value"]'),
    inputsExpences = document.querySelectorAll('.data > input[class="expenses-item"]'),
    inputsOptionalExpences = document.querySelectorAll('.data > input[class="optionalexpenses-item"]'),
    confirmExpences = document.querySelector('button[class="expenses-item-btn"]'),
    confirmOptionalExpences = document.querySelector('button[class="optionalexpenses-btn"]'),
    calculate = document.querySelector('button[class="count-budget-btn"]'),
    inputIncome = document.querySelector('input[class="choose-income"]'),
    incomeCheckbox = document.querySelector('input#savings'),
    incomeSum = document.querySelector('input#sum'),
    incomePercent = document.querySelector('input#percent'),
    inputYear = document.querySelector('input[class="year-value"]'),
    inputMonth = document.querySelector('input[class="month-value"]'),
    inputDay = document.querySelector('input[class="day-value"]');